[package]
name = "c2pa-c"
version = "0.1.0"
edition = "2021"
authors = ["Gavin Peacock <gpeacock@adobe.com"]

[lib]
crate-type = ["cdylib"]

[dependencies]
#c2pa = {version="0.28.0", features = ["file_io", "add_thumbnails", "fetch_remote_manifests"]}
c2pa = {path="../c2pa-rs/sdk",features = ["file_io", "add_thumbnails", "fetch_remote_manifests"]}
#c2pa = {git = "https://github.com/contentauth/c2pa-rs.git", branch = "gpeacock/manifest_store_builder", features = ["file_io", "add_thumbnails", "fetch_remote_manifests"] }
pem = "3.0.2"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0.49" 

[profile.release]
strip = true         # Strip symbols from the output binary.
lto = true           # Enable link-time optimization.
# it is possible to reduce size to 6mb by using the following options
#opt-level = "z"     # Optimize for size.
#codegen-units = 1   # Reduce number of codegen units to increase optimizations.
#panic = "abort"     # Abort on panic
